-- ZENTRIQ LOGISTICS - DATABASE INITIALIZATION SCRIPT
-- Compatible with Supabase (PostgreSQL) and MySQL (with minor adjustments)

-- 1. Create Shipments Table
CREATE TABLE IF NOT EXISTS shipments (
    id TEXT PRIMARY KEY,
    "trackingNumber" TEXT UNIQUE NOT NULL,
    "senderName" TEXT NOT NULL,
    "senderPhone" TEXT,
    "receiverName" TEXT NOT NULL,
    "receiverPhone" TEXT,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    "currentLocation" TEXT,
    weight TEXT,
    dimensions TEXT,
    "serviceType" TEXT,
    status TEXT DEFAULT 'Pending',
    progress INTEGER DEFAULT 0,
    "estimatedDelivery" TEXT,
    "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Shipment Updates Table (Relational History)
CREATE TABLE IF NOT EXISTS shipment_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES shipments(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL
);

-- 3. Create Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Password Resets Table
CREATE TABLE IF NOT EXISTS password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    code TEXT NOT NULL,
    expires TIMESTAMPTZ NOT NULL,
    "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Admin (Password: admin123 - should be hashed in production)
INSERT INTO admins (email, password)
VALUES ('clarklennisdean@gmail.com', 'admin123')
ON CONFLICT (email) DO NOTHING;

-- 5. Seed Initial Data (Optional - Run if you want demo data)
-- Shipment 1
INSERT INTO shipments (id, "trackingNumber", "senderName", "senderPhone", "receiverName", "receiverPhone", origin, destination, "currentLocation", weight, dimensions, "serviceType", status, progress, "estimatedDelivery", "createdAt")
VALUES ('1', '5LWVJGX73I', 'Jason Sharon', '+44 7700 900077', 'Damjana Aupic', '+49 151 23456789', 'Leicester City, United Kingdom', 'Alzbrunnen 6, 74861 Neudenau, Germany', 'Portugal Sector', '37 kg', '45x45x40 cm', 'Secure Air Freight', 'Delayed', 45, '2025-08-01', '2025-07-28')
ON CONFLICT (id) DO NOTHING;

INSERT INTO shipment_updates (shipment_id, timestamp, location, description, status)
VALUES 
('1', 'Tue, 29 Jul 2025 11:56:26 +0000', 'Portugal Customs Node', 'Security Protocol: Deep Inspection in Progress', 'Delayed'),
('1', 'Tue, 29 Jul 2025 08:55:34 +0000', 'Portugal Transit Hub', 'Asset arrived in Portugal Sector', 'In Transit'),
('1', 'Mon, 28 Jul 2025 16:25:25 +0000', 'UK Secure Facility', 'Transit Authorization Confirmed', 'In Transit'),
('1', 'Mon, 28 Jul 2025 09:55:31 +0000', 'UK Command HQ', 'Initial Manifest Protocol Established', 'Pending')
ON CONFLICT DO NOTHING;

-- Shipment 2
INSERT INTO shipments (id, "trackingNumber", "senderName", "senderPhone", "receiverName", "receiverPhone", origin, destination, "currentLocation", weight, dimensions, "serviceType", status, progress, "estimatedDelivery", "createdAt")
VALUES ('2', 'FG5T3Y3F5T', 'Tech Logistics Corp', '+65 6789 1234', 'Global Distro Ltd', '+49 30 9876543', 'Singapore Secure Hub', 'Berlin, Germany', 'Berlin Terminal', '12.5 kg', '30x30x30 cm', 'Asset Protection', 'Out for Delivery', 85, '2025-07-30', '2025-07-26')
ON CONFLICT (id) DO NOTHING;

INSERT INTO shipment_updates (shipment_id, timestamp, location, description, status)
VALUES 
('2', 'Wed, 30 Jul 2025 08:15:00 +0000', 'Berlin, Germany', 'Dispatched for local security drop', 'Out for Delivery'),
('2', 'Tue, 29 Jul 2025 21:30:00 +0000', 'Berlin Terminal', 'Asset secured at destination terminal', 'In Transit')
ON CONFLICT DO NOTHING;

-- 4. Security: Enable RLS (Supabase Specific)
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_resets ENABLE ROW LEVEL SECURITY;

-- 5. Security: Public Read Access (Tracking)
DROP POLICY IF EXISTS "Public Read Access Shipments" ON shipments;
CREATE POLICY "Public Read Access Shipments" ON shipments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Updates" ON shipment_updates;
CREATE POLICY "Public Read Access Updates" ON shipment_updates FOR SELECT USING (true);

-- 6. Security: Admin Full Access (Development Policy)
DROP POLICY IF EXISTS "Admin Full Access Shipments" ON shipments;
CREATE POLICY "Admin Full Access Shipments" ON shipments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admin Full Access Updates" ON shipment_updates;
CREATE POLICY "Admin Full Access Updates" ON shipment_updates FOR ALL USING (true) WITH CHECK (true);
